local _, MB = ...

local defaultFont = MB.Constants.DEFAULT_FONT

MB.Defaults = {
    profile = {
        unlocked = false,
        brokerEnabled = true,
        brokerMetrics = {
            showGold = true,
            showFPS = true,
            showLatency = true,
        },
        elements = {
            time = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -120,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                dateFormat = "%Y-%m-%d",
                timeFormat = "%H:%M:%S",
                dateTimeLayout = "date_then_time",
                textColor = { r = 1, g = 1, b = 1, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            zone = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -148,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 0.8, g = 1, b = 0.8, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            coords = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -176,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 0.8, g = 0.9, b = 1, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            durability = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -204,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 1, g = 0.85, b = 0.5, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            memory = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -232,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 0.95, g = 0.75, b = 1, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            gold = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -260,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 1, g = 0.82, b = 0.2, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            fps = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -288,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 0.6, g = 1, b = 0.6, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
            latency = {
                enabled = true,
                point = "TOP",
                relativePoint = "TOP",
                x = 0,
                y = -316,
                font = defaultFont,
                fontSize = 13,
                showLabel = true,
                showBackground = true,
                showBorder = true,
                textColor = { r = 0.6, g = 0.8, b = 1, a = 1 },
                backgroundColor = { r = 0, g = 0, b = 0, a = 0.45 },
                borderColor = { r = 0.4, g = 0.4, b = 0.4, a = 1 },
                alpha = 1,
                scale = 1,
            },
        },
    },
}
